### ISSUE TITLE
display results ordered by years and trimester

### ISSUE THREAD

**Issue by vdias38** [meumobi/IRmobi#321]
### Expected behaviour

![Itau_-_meumobi___Investor__Benchmark_-_Google_Docs](https://user-images.githubusercontent.com/9011612/55159463-fae82300-5158-11e9-873d-8b9359bfa84e.png)

**Comment by vdias38** [comment]
I've created a results type on sitebuilder.

You can test it on following [feed](http://mobi.comunique-se.com.br/api/biosevpt.mobi.comunique-se.com.br/categories/710/items)

**Comment by danconte72** [comment]
### UI
- We use  mobile-angular-ui on [latest release](https://github.com/mcasimir/mobile-angular-ui) on irmobi
- [accordion](http://mobileangularui.com/demo/#/accordion)
- [tabs](http://mobileangularui.com/docs/tabs/)

There are the options
- Tabs for years - Accordion for quarters
  - List latest 4/5 years on top (width limited)
  - Each tab with 4 accordions 
  - On accordion must show items ordered by date - latest up

- Accordion for years - Tab for quarters - my option because we can show all years 
  - List all available years as accordion  (height unlimited)
  - Each accordion with 4 tabs 
  - On tab must show items ordered by date - latest up

- Accordion for years - Accordion for quarters
  - can be confused to users
- Tabs for years - Tabs for quarters
  - can be confused to users
  - tabs inside tabs must be avoid
[https://material.io/design/components/tabs.html#placement](![image](https://user-images.githubusercontent.com/32454870/55347050-40bf2700-548a-11e9-916c-22939e376ad2.png))

**Comment by danconte72** [comment]
### Feature
- Source:
  - Feed contains results;
  - results ordered by published date (latest before), date is in timestamp format (ex: 1550196000);
- Destination:
  - results classified by:
    - year
    - quarter
  - results ordered into quarter  by published date (latest before)

**Comment by danconte72** [comment]
### What code must to do 
- Read feed;
- It type==results render a results-list;
- results-list:
  - for each result
    - [get](https://stackoverflow.com/questions/23104873/extract-month-or-day-or-year-from-timestamp) year and month from timestamp;
    - get quarter based on month ( quarter = Math.floor(month/4))
    - set year and quarter ;
  - group results by year;
  - for each year render a year-element;
- year-element:
  - group year results by quarter;
  - for each quarter render a quarter-results-list;
- quarter-results-list:
  - show results ordered;
  - render for each result a item-headline;

#### How to distribute this features into code?

**Comment by danconte72** [comment]
### structure propose
- results-list:
  - results/list.html;
    - for each year render year-results-component passing year results;
  - controllers/results_controller.js;
    - classify results (year, quarter);
    - group results by year;
- year-element:
  - components/year-results-component.js;
   - group  results by quarter;
  - widgets/year-result.html;
    - for each quarter render a quarter tab/accordion;
    - into each quarter render a list of results;
    - each result is a item-headline;

#### I didn't understand how to
- If type==results render a results-list

**Comment by danconte72** [comment]
## Feature
- Source:
  - Feed contains results;
  - results ordered by published date (latest before);
  - Title in the following pattern: 
    - '[q]T[yy]' for pt - i.e. 1T18 
    - '[q]Q[yy]' for en - i.e. 3Q17
- Destination:
  - results classified by:
    - year
  - results ordered into year  by published date (latest before)
### UI
- We use  mobile-angular-ui on [latest release](https://github.com/mcasimir/mobile-angular-ui) on irmobi
- [accordion](http://mobileangularui.com/demo/#/accordion)

#### Master-detail pattern
- Accordion for years
  - Each year list the quarter results;
  - results linked to results-details (items-details);

#### Sketch 
![IMG_5997](https://user-images.githubusercontent.com/32454870/55400857-5df50380-5525-11e9-930b-59098baeba0c.jpg)
 
### Code
app.js
```js
	when('/results/:id/page/:page', {
		controller: 'ResultsListController',
		controllerAs: 'vm',
		templateUrl: 'results/list.html',
		canReload: true,
		resolve: {
			viewName: resolveCategory
		}
	}).
 	when('/results/:id', {
		controller: 'ResultsListController',
		controllerAs: 'vm',
		templateUrl: 'results/list.html',
		canReload: true,
		resolve: {
			viewName: resolveCategory
		}
	}).
```
controllers/results_controler.js
```js

....

**Comment by vdias38** [comment]
I've published 

## Set year property

```
decorateItem(item) {
  item.year = this.getYearFromString(item.title)
  return item;
}
```

## Get items grouped per year

`meuCloud.helpers.lookupByToken(results, 'year')`

Display latest 4 years on home (headlines) and all on list (to prevent pagination)
